### ISSUE TITLE
SpRL: Stanford NLP issue

### ISSUE THREAD

**Issue by PattyBG** [CogComp/saul#474]
Hi :)

I am working on the SpRL task. I downloaded the data but I still have the following issue:

[error] Reading POS tagger model from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1,5 sec].
[error] Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [0,7 sec].

What should I do ? Where can I download this files and where should I put them in my path ?
Thanks a lot for your help.

**Comment by danyaljj** [comment]
For some reason Stanford prints it as error msg, but it's actually not an error (just a normal load msg).
