### ISSUE TITLE
SpRL: Multiple words in trajector and landmark

### ISSUE THREAD

**Issue by EloiZ** [CogComp/saul#477]
Hi,
is there any reason why Saul does not handle landmark or trajector that contain several words?
Training and testing both work fine, but when I want to extract relations on new data, it never outputs triplets whose landmark (or trajector) contain several words. Note that training data has a lot of triplets with multiple words in the landmark of trajector.

For example:
training data: 
[A blond girl]{trajector} [in front of]{spatial indicator} [a blue house]{landmark}
...

output observed on test data:
A blond [girl]{trajector} [in front of]{spatial indicator} a blue [house]{landmark}

Also this misses a lot of relations (the one with long landmarks and/or trajector)

I use version="2012"
and get the output with the following script in SpRLApp.scala
```
SpRLDataModel.relations().filter(r => classifier(r).equalsIgnoreCase("Gold")).foreach(r => {
        writer.println(r.getSentence.getText)                                   
        writer.println(s"${r.getTrajector.getText}")                                        
        writer.println(r.getTrajector.getSpan)                                  
        writer.println(s"${r.getSpatialIndicator.getText}")                     
        writer.println(r.getSpatialIndicator.getSpan)
```

Thanks a lot for any help!

**Comment by EloiZ** [comment]
Also, maybe it's a related problem, but I'm not able to get the same kind of results as presented [here](https://www.cs.york.ac.uk/semeval-2012/task3/index.php%3Fid=results.html) (on the same data).
I have a high precision (almost 100%) and very low recall (about 30%) for trajectors, landmarks and spatial indicators.
Am I supposed to use the default parameters for the SVM classifier and the default feature i.e. `relationFeatures = List(JF2_1, JF2_2, JF2_3, JF2_4, JF2_5, JF2_6, JF2_7, JF2_8, JF2_9, JF2_10, JF2_11, JF2_12, JF2_13, JF2_14, JF2_15, BH1)`
Thanks a lot!
Best,

**Comment by Rahgooy** [comment]
Hi,

Please note that the candidate generation for relation arguments(Tr and Lm) is based on tokens, not phrases, you can find it [here](https://github.com/CogComp/saul/blob/master/saul-examples/src/main/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SpatialRoleLabeling/SpRLSensors.scala#L30).

About the results, we have published the model's results on 2012 data [here](https://github.com/CogComp/saul/tree/master/saul-examples/src/main/scala/edu/illinois/cs/cogcomp/saulexamples/nlp/SpatialRoleLabeling#test-results-for-semeval-2012-data). This results obtained by using all features except SRL feature(`JF2_12` ) as I mentioned in [this comment](https://github.com/CogComp/saul/issues/476#issuecomment-296694459)

**Comment by EloiZ** [comment]
Thanks for your answer, 
I could reproduce the results
