### ISSUE TITLE
Logging works only with Scala "2.11.7"

### ISSUE THREAD

**Issue by kordjamshidi** [CogComp/saul#483]
Is this true? And for the same reason, then no App can run if the Scala version does not match.

**Comment by danyaljj** [comment]
Not sure. What is the error you're observing?

**Comment by kordjamshidi** [comment]
When using ```scalaVersion := "2.12.2"``` : 
 ```Exception in thread "main" java.lang.NoSuchMethodError: edu.illinois.cs.cogcomp.saul.util.Logging.$init$(Ledu/illinois/cs/cogcomp/saul/util/Logging;)V```

**Comment by danyaljj** [comment]
Is this a scala version set in a different project (using Saul as dependency), or inside Saul project?

**Comment by kordjamshidi** [comment]
using Saul as a dependency.

**Comment by danyaljj** [comment]
So in this case (using Saul as dependency), to the extent my knowledge goes, in general in Scala your (scala) dependencies have to be compiled/generated with the same Scala version you're using. So if you want to use Saul with different Scala versions, we have to deploy it with that version (and include the right version in our project).

**Comment by kordjamshidi** [comment]
I see. This is an interesting point, thanks.

**Comment by kordjamshidi** [comment]
FYI. @Abi1024
